# This is a password generator project which provides a random shuffle password

# Firstly importing random library
import random

# List of characters, symbols and numbers
characters = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u",
              "v", "w", "x", "y", "z", "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P",
              "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"]

symbols = ["!", "@", "#", "$", "%", "^", "&", "*", "(", ")", "-", "+", "+"]

numbers = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]

# Input for characters, symbols and numbers
total_character = int(input("Enter how many charcters do you want : "))
total_symbol = int(input("Enter how many symbols you required : "))
total_number = int(input("Enter how many numbers you required : "))

# An empty list to store the items
password = []

# For loop for appending characters items in list which is randomly generated by user inputs
for i in range(total_character):
    password.append(random.choice(characters))

# For loop for appending symbols items in list which is randomly generated by user inputs
for i in range(total_symbol):
    password.append(random.choice(symbols))

# For loop for appending numbers items in list which is randomly generated by user inputs
for i in range(total_number):
    password.append(random.choice(numbers))

# After that we shuffle the list
random.shuffle(password)

# The shuffle list will stored in an empty string which is created as new_password.
new_password = ""

# For loop to iterate the password list and stored it in new_password which is string
for i in password:
    new_password += i


print(f"Your new and highly secured password is : {new_password}")









